# This is a child workflow
name: Integration

on:
  workflow_call: # Make this workflow callable by other workflows

jobs:
  # Stage 1: Parallel jobs (Build_Job and Test_Job)
  Build_Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Performing build"

  Test_Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Performing tests"
